### ISSUE TITLE
New downloadable release or does README need updating?

### ISSUE THREAD

**Issue by badrange** [heddn/php-pass-provider#8]
Hi and thanks for making this helpful pass provider!

I noticed that the README.md file states that one should download the most recent jar file from Releases, but there hasn't been a new release since 1.0 was published even though I see that some PRs have been merged. 

Should I hope for a new release or is the README out of date?

Cheers

**Comment by heddn** [comment]
new things have been merged, yes. but that was only bumping pom.xml dependencies. The actual code here has not changed.

**Comment by badrange** [comment]
Thank you for the quick reply @heddn; I interpret your answer so that the package will continue working also with newer versions of Keycloak - I'm just about to upgrade our system.

**Comment by heddn** [comment]
That should work. If it doesn't:

> If you need to rebuild the JAR file for use with a more modern version of Java, simply `mvn clean install` will generate the required artifacts.

**Comment by badrange** [comment]
Thanks! I'll close this issue then!
